export const AGREGAR_PUBLICACION = 'AGREGAR_PUBLICACION';
export const AGREGAR_PUBLICACION_EXITO = 'AGREGAR_PUBLICACION_EXITO';
export const AGREGAR_PUBLICACION_ERROR = 'AGREGAR_PUBLICACION_ERROR';

export const COMENZAR_DESCARGA_PUBLICACIONES = 'COMENZAR_DESCARGA_PUBLICACIONES';
export const DESCARGAR_PUBLICACIONES_EXITO = 'DESCARGAR_PUBLICACIONES_EXITO';
export const DESCARGAR_PUBLICACIONES_ERROR = 'DESCARGAR_PUBLICACIONES_ERROR';
