export const AGREGAR_PUBLICACION = 'AGREGAR_PUBLICACION';
export const AGREGAR_PUBLICACION_EXITO = 'AGREGAR_PUBLICACION_EXITO';
export const AGREGAR_PUBLICACION_ERROR = 'AGREGAR_PUBLICACION_ERROR';

export const COMENZAR_DESCARGA_PUBLICACIONES = 'COMENZAR_DESCARGA_PUBLICACIONES';
export const DESCARGAR_PUBLICACIONES_EXITO = 'DESCARGAR_PUBLICACIONES_EXITO';
export const DESCARGAR_PUBLICACIONES_ERROR = 'DESCARGAR_PUBLICACIONES_ERROR';

export const OBTENER_PUBLICACION = 'OBTENER_PUBLICACION';
export const PUBLICACION_OBTENIDA_EXITO = 'PUBLICACION_OBTENIDA_EXITO';
export const PUBLICACION_OBTENIDA_ERROR = 'PUBLICACION_OBTENIDA_ERROR';
